# Generated by Django 6.0.3 on 2026-03-22 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='monitoring.region')),
            ],
            options={
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clients_count', models.PositiveIntegerField()),
                ('energy_usage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ac_mode', models.CharField(choices=[('OFF', 'OFF'), ('ECO', 'ECO'), ('ON', 'ON')], max_length=3)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='monitoring.agency')),
            ],
        ),
    ]
