# Generated by Django 6.0.3 on 2026-03-29 13:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='energy_usage',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-30.0')), django.core.validators.MaxValueValidator(Decimal('55.0'))]),
        ),
        migrations.AddConstraint(
            model_name='sensordata',
            constraint=models.UniqueConstraint(fields=('agency', 'timestamp'), name='sensor_data_agency_timestamp_uniq'),
        ),
    ]
