# Generated by Django 6.0.3 on 2026-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_sensor_data_uniq_and_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(choices=[('AGENCE', 'Agence'), ('CENTRE_AFFAIRES', "Centre d'affaires"), ('DIRECTION_REGIONALE', 'Direction régionale'), ('SIEGE', 'Siège'), ('SUCCURSALE', 'Succursale'), ('GAB', 'GAB')], default='AGENCE', max_length=30),
        ),
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='agency',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
